[project]
name = "streamlink-plugin-greenchannel"
version = "0.1.0"
description = "Streamlink plugin for GreenCH"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "streamlink>=7.1.3",
]

[project.entry-points."streamlink.plugins"]
greenchannel = "greenchannel.greenchannel"
